import = [ "~/.config/alacritty/themes/themes/gruvbox_material_hard_dark.toml" ]

[font]
size = 20

[font.normal]
family = "Iosevka Term Nerd Font"

[window]
decorations = "Full"
startup_mode = "Maximized"
