#!/bin/bash

option=$(echo -e 'Lock\nShutdown\nReboot' | rofi -dmenu -i -p "Power prompt")

case $option in "Shutdown")
    exec shutdown now
    ;;
"Reboot")
    exec reboot
    ;;
"Lock")
    exec waylock
    ;;
esac
