#!/bin/bash

while getopts 's' option; do
    case $option in
        s)
            save=1
            ;;
    esac
done

if [ $save ]; then
    grim -g "$(slurp -w 0)"
else
    grim -g "$(slurp -w 0)" - | wl-copy
fi

