#!/bin/bash

# Startup
xsetroot -cursor_name left_ptr &
pgrep -x sxhkd >/dev/null || sxhkd &

~/.config/bspwm/scripts/bspwmcolors
~/.config/polybar/launch.sh

# bspc monitor -d Δ Θ Π Ψ Ω

if [[ $(xrandr -q | grep 'HDMI-0 connected') ]]; then
	bspc monitor DVI-D-0 -d 1 2 3 4 5
	bspc monitor HDMI-0 -d 6 7 8
else
	bspc monitor -d 1 2 3 4 5
fi

bspc config border_width 0
bspc config window_gap 0

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config single_monocle false
bspc config gapless_monocle false
bspc config focus_follows_pointer true

# Rules
bspc rule -a qutebrowser desktop=^6
bspc rule -a Brave-browser desktop=^7
bspc rule -a Steam state=floating
bspc rule -a discord desktop=^8 state=floating
bspc rule -a Zathura state=tiled
bspc rule -a Emacs state=tiled
bspc rule -a Float state=floating
bspc rule -a dmenu monitor=^1
bspc rule -a rofi monitor=^1
