#! /bin/sh

# Startup
xsetroot -cursor_name left_ptr &
pgrep -x sxhkd > /dev/null || sxhkd &
~/.config/polybar/launch.sh
~/scripts/bspwm/bspwmcolors.sh

bspc monitor -d Δ Θ Π Ψ Ω

bspc config border_width         0
bspc config window_gap           5
bspc config top_padding          0

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc config focus_follows_pointer true

# Rules
bspc rule -a spotify-tui desktop=^4 state=floating
bspc rule -a Steam state=floating
bspc rule -a discord desktop=^5 state=floating
bspc rule -a Zathura state=tiled
bspc rule -a Emacs state=tiled
bspc rule -a Float state=floating
