#!/bin/bash

# Startup
xsetroot -cursor_name left_ptr &
pgrep -x sxhkd >/dev/null || sxhkd &
~/.fehbg &

~/.config/bspwm/scripts/bspwmcolors

# For some reason we have to wait a bit before starting polybar, otherwise
# it doesn't show properly (although it starts just fine).
sleep 1

~/.config/polybar/launch.sh

# if [[ $(xrandr -q | grep 'HDMI2 connected') ]]; then
#   bspc monitor eDP1 -d 1 2 3 4 5
#   bspc monitor HDMI2 -d 1 2 3 4 5
# else
#   bspc monitor -d 1 2 3 4 5 7 8 9 10
# fi

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width 1
bspc config window_gap 0

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config single_monocle true
bspc config gapless_monocle false
bspc config focus_follows_pointer true
bspc config merge_overlapping_monitors true
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true

# Rules
bspc rule -a qutebrowser desktop=1
bspc rule -a Brave-browser desktop=1
bspc rule -a Steam state=floating
bspc rule -a discord desktop=5 state=floating
bspc rule -a Zathura state=tiled
bspc rule -a Emacs state=tiled
bspc rule -a Surf state=tiled
bspc rule -a Float state=floating
bspc rule -a dmenu monitor=1
bspc rule -a rofi monitor=1
bspc rule -a gnome-calculator state=floating
