return {
  "nvim-treesitter/nvim-treesitter",
  branch = "master",
  opts = {
    ensure_installed = {
      "bash",
      "bicep",
      "c",
      "diff",
      "dockerfile",
      "eex",
      "elixir",
      "gitcommit",
      "go",
      "gomod",
      "gosum",
      "html",
      "javascript",
      "jsdoc",
      "json",
      "lua",
      "luadoc",
      "markdown",
      "markdown_inline",
      "python",
      "query",
      "regex",
      "toml",
      "tsx",
      "typescript",
      "vim",
      "vimdoc",
      "xml",
      "yaml",
    },
  },
}
