return {
  "nvim-treesitter/nvim-treesitter",
  branch = "main",
  lazy = false,
  build = ":TSUpdate",
  opts = {
    install_dir = vim.fn.stdpath("data") .. "/site",
  },
  init = function()
    require("nvim-treesitter").install({
      "bash",
      "bicep",
      "c",
      "diff",
      "dockerfile",
      "eex",
      "elixir",
      "gitcommit",
      "go",
      "gomod",
      "gosum",
      "html",
      "javascript",
      "jsdoc",
      "json",
      "lua",
      "luadoc",
      "markdown",
      "markdown_inline",
      "python",
      "query",
      "regex",
      "toml",
      "tsx",
      "typescript",
      "vim",
      "vimdoc",
      "xml",
      "yaml",
    })
  end,
}
